In [281]:
import pandas as pd
import numpy as np
import os
import openpyxl as opx

In [185]:


jsonDF = pd.DataFrame()
for file_name in os.listdir(r"C:\Users\lexas\Documents\project\json_dump"):
    jsonDemoDF = pd.read_json("C:\\Users\\lexas\\Documents\\project\\json_dump" + "\\" + file_name , lines = True)
    jsonDemoDF = jsonDemoDF[jsonDemoDF['grbs'].apply(lambda x: x["fullName"] == 'МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ')]
    jsonDF = jsonDF.append(jsonDemoDF, ignore_index = True)

In [229]:
jsonDF = jsonDF.filter( ['receiver' , 'grbs' , 'plansNormalized'] , axis = 1)
jsonDF

,receiver,grbs,plansNormalized
0,"[{'budgetName': '', 'fullName': 'Общество с ог...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004121840264722811', 'purpose'..."
1,"[{'budgetName': '', 'fullName': 'Акционерное о...","{'okopf': '20903', 'fullName': 'МИНИСТЕРСТВО П...",[]
2,"[{'budgetName': '', 'fullName': 'АКЦИОНЕРНОЕ О...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004111950168580812', 'purpose'..."
3,"[{'budgetName': '', 'fullName': '""Сетелем Банк...","{'okopf': '20903', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004121610165200810', 'purpose'..."
4,"[{'budgetName': '', 'fullName': 'Акционерное о...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004121840168844452', 'purpose'..."
...,...,...,...
12590,"[{'budgetName': '', 'fullName': 'Общество с ог...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '0200412165П368851811', 'purpose'..."
12591,"[{'budgetName': '', 'fullName': 'Общество с ог...","{'okopf': '20903', 'fullName': 'МИНИСТЕРСТВО П...",[]
12592,"[{'budgetName': '', 'fullName': 'Общество с ог...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004121620560980811', 'purpose'..."
12593,"[{'budgetName': '', 'fullName': 'Закрытое акци...","{'okopf': '75104', 'fullName': 'МИНИСТЕРСТВО П...","[{'kbkCode': '02004121610460980811', 'purpose'..."
12594,"[{'budgetName': '', 'fullName': 'Акционерное о...","{'okopf': '20903', 'fullName': 'МИНИСТЕРСТВО П...",[]

In [279]:
history = ['3213242141', '124323214']
DFBase =  pd.DataFrame()  #{"fullName" :['zero'], 'OGRN' : ["non"], 'OKVD2' : ["21.12.32.42"], "OKPD2" : ['21.12.23.43'] , 'history' : []}
#DFBase['history'].append(history)

okvd2DataList = ['dasdsaf', 'fasdfdsa']
fullNameList = ['пвпывп', 'авыпыв']
ogrnList = ['17182839', '1234125']

okvd2DataList = pd.Series(data = fullNameList)
fullNameList = pd.Series(data = fullNameList)
ogrnList = pd.Series(data = ogrnList)


for i in range(len(jsonDF)):
    fullNameList[i] = jsonDF.receiver[i][0]['fullName']
    ogrnList[i] = jsonDF.receiver[i][0]['ogrn']

0        1157847410753
1
2        1127847272629
3
4
             ...
12590
12591
12592
12593    1116952057914
12594
Length: 12595, dtype: object

In [280]:


DFBase['fullName'] = fullNameList
DFBase['ogrn'] = ogrnList

                                                fullName           ogrn
0      Общество с ограниченной ответственностью "Пола...  1157847410753
1                  Акционерное общество "ЮниКредит Банк"
2               АКЦИОНЕРНОЕ ОБЩЕСТВО "ДИПОЛЬ ТЕХНОЛОГИИ"  1127847272629
3      "Сетелем Банк" Общество с ограниченной ответст...
4      Акционерное общество "Объединенная судостроите...
...                                                  ...            ...
12590  Общество с ограниченной ответственностью "ЯРУС...
12591  Общество с ограниченной ответственностью "Изол...
12592  Общество с ограниченной ответственностью "Новы...
12593  Закрытое акционерное общество "Тверской экскав...  1116952057914
12594  Акционерное общество "Кинешемская прядильно-тк...

[12595 rows x 2 columns]

In [282]:
DFBase.to_json(r"C:\Users\lexas\Documents\project\json_BD\MainDataBase.json", orient = "records", lines=True)

In [190]:
jsonDF.to_json(r"C:\Users\lexas\Documents\project\json_BD\jsonBD.json", orient = "records", lines=True)